dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.3.2
  - smartcontractkit/chainlink-brownie-contracts@0.3.0
compiler:
  solc:
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.3.2"
      - "@chainlink=smartcontractkit/chainlink-brownie-contracts@0.3.0"
